nuget:
  account_feed: true

version: 1.0.{build}-rc1

before_build:
 - nuget restore
 - cmd: set BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%

after_build:
 - nuget pack NetSDK\Splitio.nuspec -Version %appveyor_build_version%
 

artifacts:
 - path: '**\Splitio.*.nupkg'
   name: splitio-nuget
 
deploy:
 - provider: Environment
   name: NugetPublish
   on:
    branch: master

 - provider: Environment
   name: NugetPublish2
   on:
    branch: development
 
after_deploy:
 - if($env:APPVEYOR_REPO_BRANCH -eq "development"){nuget delete splitio-nuget  %appveyor_build_version% -Source nuget.org -ApiKey $env:nugetkey -NonInteractive}

#notifications:
#  - provider: Slack
#    auth_token:
#      secure: xxxxxxxxxx
#    channel: xxxxxxxxxx
#template: "<{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}> Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}: _{{commitMessage}}_"
