nuget:
  account_feed: true

version: 3.3.0-rc{build}

configuration: Release

before_build:
 - nuget restore
 - cmd: set BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
 
after_build:
 - nuget pack NetSDK\Splitio.csproj -Version %appveyor_build_version%
 - nuget pack NetSDK\Splitio.Redis.csproj -Version %appveyor_build_version%

artifacts:
 - path: '**\Splitio.*.nupkg'
   name: splitio-nuget

deploy:
 - provider: Environment
   name: NugetPublish
   on:
    branch: master
