nuget:
  account_feed: true

version: 0.0.4.5

before_build:
 - nuget restore
 - cmd: set BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%

after_build:
 - nuget pack NetSDK\Splitio.nuspec -Version %appveyor_build_version%

artifacts:
 - path: '**\splitio.0.0.4.5.nupkg'
#notifications:
#  - provider: Slack
#    auth_token:
#      secure: xxxxxxxxxx
#    channel: xxxxxxxxxx
#template: "<{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}> Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}: _{{commitMessage}}_"
